name: Check & fix stilyng

on: [push, pull_request]

jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Run Laravel Pint
        uses: aglipanci/laravel-pint-action@1.0.0
        with:
          preset: laravel

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply fixes from Pint
          commit_options: '--no-verify'